"""
Unit tests for invoice schema validators.
"""

import pytest
from decimal import Decimal
from datetime import datetime
from pydantic import ValidationError

from Backend.api.accounting.invoices.schemas import InvoiceCreate
from Backend.models.accounting.invoice_tax_detail import InvoiceTaxDetailCreate


class TestInvoiceCreateValidators:
    """Test InvoiceCreate schema validators."""

    def test_valid_invoice_create(self):
        """Test creating valid invoice."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test invoice",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.invoice_number == "INV-001"
        assert invoice.amount == Decimal('1000.00')

    def test_invoice_number_optional(self):
        """Test invoice_number is optional (auto-generated if not provided)."""
        # Act - Create invoice without invoice_number
        invoice = InvoiceCreate(
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert - invoice_number should be None (will be auto-generated by service)
        assert invoice.invoice_number is None

    def test_amount_required(self):
        """Test amount is required."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                description="Test",
                issue_date=datetime.now(),
                due_date=datetime.now()
            )
        
        assert "amount" in str(exc_info.value).lower()

    def test_description_required(self):
        """Test description is required."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                issue_date=datetime.now(),
                due_date=datetime.now()
            )
        
        assert "description" in str(exc_info.value).lower()

    def test_dates_required(self):
        """Test issue_date and due_date are required."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                description="Test"
            )
        
        errors = str(exc_info.value).lower()
        assert "issue_date" in errors or "due_date" in errors

    def test_taxes_optional(self):
        """Test taxes field is optional."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.taxes is None or invoice.taxes == []

    def test_line_items_optional(self):
        """Test line_items field is optional."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.line_items is None or invoice.line_items == []

    def test_property_id_optional(self):
        """Test property_id is optional."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.property_id is None

    def test_tenant_id_optional(self):
        """Test tenant_id is optional."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.tenant_id is None

    def test_recipient_type_optional(self):
        """Test recipient_type is optional."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.recipient_type is None


class TestInvoiceTaxDetailValidators:
    """Test InvoiceTaxDetail schema validators."""

    def test_valid_tax_detail(self):
        """Test creating valid tax detail."""
        # Act
        tax = InvoiceTaxDetailCreate(
            tax_name="HST",
            tax_rate=Decimal('13.00'),
            tax_amount=None
        )
        
        # Assert
        assert tax.tax_name == "HST"
        assert tax.tax_rate == Decimal('13.00')

    def test_tax_name_required(self):
        """Test tax_name is required."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceTaxDetailCreate(
                tax_rate=Decimal('13.00')
            )
        
        assert "tax_name" in str(exc_info.value).lower()

    def test_tax_rate_required(self):
        """Test tax_rate is required."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceTaxDetailCreate(
                tax_name="HST"
            )
        
        assert "tax_rate" in str(exc_info.value).lower()

    def test_tax_amount_optional(self):
        """Test tax_amount is optional."""
        # Act
        tax = InvoiceTaxDetailCreate(
            tax_name="HST",
            tax_rate=Decimal('13.00')
        )
        
        # Assert
        assert tax.tax_amount is None

    def test_tax_amount_can_be_zero(self):
        """Test tax_amount can be explicitly set to zero."""
        # Act
        tax = InvoiceTaxDetailCreate(
            tax_name="Exempt",
            tax_rate=Decimal('0.00'),
            tax_amount=Decimal('0.00')
        )
        
        # Assert
        assert tax.tax_amount == Decimal('0.00')


class TestInvoiceCreateRecipientValidation:
    """Test InvoiceCreate recipient validation logic."""

    def test_invoice_with_multiple_recipients_error(self):
        """Test validation error when multiple recipients provided."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                description="Test",
                issue_date=datetime.now(),
                due_date=datetime.now(),
                tenant_id=1,
                vendor_id=2  # Multiple recipients
            )
        
        assert "exactly one recipient" in str(exc_info.value).lower()

    def test_invoice_with_no_recipient_allowed(self):
        """Test invoice with no recipient is allowed for backward compatibility."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now()
        )
        
        # Assert
        assert invoice.tenant_id is None
        assert invoice.vendor_id is None

    def test_recipient_type_tenant_requires_tenant_id(self):
        """Test recipient_type='tenant' requires tenant_id."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                description="Test",
                issue_date=datetime.now(),
                due_date=datetime.now(),
                recipient_type="tenant"
                # Missing tenant_id
            )
        
        assert "tenant_id required" in str(exc_info.value).lower()

    def test_recipient_type_ownership_entity_requires_id(self):
        """Test recipient_type='ownership_entity' requires ownership_entity_id."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                description="Test",
                issue_date=datetime.now(),
                due_date=datetime.now(),
                recipient_type="ownership_entity"
                # Missing ownership_entity_id
            )
        
        assert "ownership_entity_id required" in str(exc_info.value).lower()

    def test_recipient_type_vendor_requires_vendor_id(self):
        """Test recipient_type='vendor' requires vendor_id."""
        # Act & Assert
        with pytest.raises(ValidationError) as exc_info:
            InvoiceCreate(
                invoice_number="INV-001",
                amount=Decimal('1000.00'),
                description="Test",
                issue_date=datetime.now(),
                due_date=datetime.now(),
                recipient_type="vendor"
                # Missing vendor_id
            )
        
        assert "vendor_id required" in str(exc_info.value).lower()

    def test_invoice_with_tenant_recipient(self):
        """Test valid invoice with tenant recipient."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now(),
            recipient_type="tenant",
            tenant_id=1
        )
        
        # Assert
        assert invoice.tenant_id == 1
        assert invoice.recipient_type == "tenant"

    def test_invoice_with_ownership_entity_recipient(self):
        """Test valid invoice with ownership entity recipient."""
        # Arrange
        from uuid import uuid4
        entity_id = uuid4()
        
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now(),
            recipient_type="ownership_entity",
            ownership_entity_id=entity_id
        )
        
        # Assert
        assert invoice.ownership_entity_id == entity_id
        assert invoice.recipient_type == "ownership_entity"

    def test_invoice_with_vendor_recipient(self):
        """Test valid invoice with vendor recipient."""
        # Act
        invoice = InvoiceCreate(
            invoice_number="INV-001",
            amount=Decimal('1000.00'),
            description="Test",
            issue_date=datetime.now(),
            due_date=datetime.now(),
            recipient_type="vendor",
            vendor_id=5
        )
        
        # Assert
        assert invoice.vendor_id == 5
        assert invoice.recipient_type == "vendor"

